/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package domain.reservation;

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import org.apache.commons.lang3.Validate;

/**
 * Uniquely identifies a particular cargo. Automatically generated by the
 * application.
 */
@Embeddable
public class ReservationNumber implements Serializable {

    private static final long serialVersionUID = 1L;
    @Column(name = "reservation_number", unique = true, updatable = false)
    private String id;

    public ReservationNumber() {
    }

    public ReservationNumber(String id) {
        Validate.notNull(id);
        this.id = id;
    }

    public String getIdString() {
        return id;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }

        ReservationNumber other = (ReservationNumber) o;

        return sameValueAs(other);
    }

    @Override
    public int hashCode() {
        return id.hashCode();
    }

    boolean sameValueAs(ReservationNumber other) {
        return other != null && this.id.equals(other.id);
    }

    @Override
    public String toString() {
        return id;
    }
}
